# Generated by Django 5.2.4 on 2025-08-03 11:12

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='category_images/', verbose_name='تصویر دسته\u200cبندی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی فایل',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای فایل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('file', models.FileField(upload_to=core.models.file_upload_path, verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('document', 'سند'), ('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صوت'), ('archive', 'آرشیو'), ('code', 'کد'), ('other', 'سایر')], max_length=20, verbose_name='نوع فایل')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.filecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ پرداختی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه تراکنش')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خرید')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.file', verbose_name='فایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'خرید',
                'verbose_name_plural': 'خریدها',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'file')},
            },
        ),
    ]
